// =============================================================================
// 정책자금 프로그램 데이터베이스
// =============================================================================

export interface FundProgram {
  id: string;
  name: string;
  agency: string;           // 운영기관
  category: string;         // 분류 (R&D, 사업화, 수출, 정책자금 등)
  maxAmount: string;        // 최대 지원 금액 표시
  maxAmountNum: number;     // 비교용 숫자 (원)
  supportType: string;      // 지원 유형 (출연금, 융자, 보증 등)
  period: string;           // 지원 기간
  requirements: FundRequirement[];
  website: string;
  description: string;
}

export interface FundRequirement {
  field: string;
  label: string;
  check: 'required' | 'preferred' | 'bonus';
  description: string;
}

export const FUND_PROGRAMS: FundProgram[] = [
  {
    id: 'tips',
    name: 'TIPS (민간투자주도형 기술창업지원)',
    agency: '중소벤처기업부',
    category: 'R&D',
    maxAmount: '최대 10억원',
    maxAmountNum: 1_000_000_000,
    supportType: '출연금(R&D) + 엔젤매칭',
    period: '3년',
    requirements: [
      { field: 'yearsFromFounding', label: '업력 7년 이내', check: 'required', description: '설립 후 7년 이내 기업' },
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasPatent', label: '기술력 보유', check: 'preferred', description: '특허, 기술 등 핵심 기술 보유' },
      { field: 'hasResearchInstitute', label: '연구소/전담부서', check: 'bonus', description: '기업부설연구소 또는 R&D 전담부서' },
      { field: 'hasVentureCert', label: '벤처기업 인증', check: 'bonus', description: '벤처기업 확인서 보유 시 가산' },
    ],
    website: 'https://www.jointips.or.kr',
    description: 'TIPS 운영사의 투자를 받은 기업에 R&D 자금을 매칭 지원. 민간 엔젤투자 연계 필수.',
  },
  {
    id: 'startup_growth',
    name: '창업성장기술개발사업',
    agency: '중소벤처기업부',
    category: 'R&D',
    maxAmount: '최대 3억원',
    maxAmountNum: 300_000_000,
    supportType: '출연금',
    period: '2년',
    requirements: [
      { field: 'yearsFromFounding', label: '업력 7년 이내', check: 'required', description: '창업 7년 이내 중소기업' },
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasRnd', label: 'R&D 역량', check: 'preferred', description: 'R&D 투자실적 또는 연구인력 보유' },
      { field: 'hasPatent', label: '기술력 보유', check: 'bonus', description: '특허, 논문 등 기술성과물' },
    ],
    website: 'https://www.smtech.go.kr',
    description: '창업 초기 기술개발을 지원하는 정부 R&D 과제. 디딤돌/전략형 트랙.',
  },
  {
    id: 'export_voucher',
    name: '수출바우처',
    agency: '중소벤처기업부 / KOTRA',
    category: '수출',
    maxAmount: '최대 1억원',
    maxAmountNum: 100_000_000,
    supportType: '바우처(수출활동비)',
    period: '1년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'isExporter', label: '수출 의지/실적', check: 'preferred', description: '수출 실적 또는 수출 계획 보유' },
      { field: 'hasRevenue', label: '매출 실적', check: 'required', description: '일정 매출 실적 보유' },
      { field: 'hasVentureCert', label: '벤처/이노비즈', check: 'bonus', description: '인증기업 가산점' },
    ],
    website: 'https://www.exportvoucher.com',
    description: '해외마케팅, 통번역, 해외인증 등 수출활동에 바우처 지원.',
  },
  {
    id: 'sme_policy_fund',
    name: '중소기업 정책자금 (직접대출)',
    agency: '중소벤처기업진흥공단',
    category: '정책자금',
    maxAmount: '최대 100억원',
    maxAmountNum: 10_000_000_000,
    supportType: '저금리 융자',
    period: '최대 8년 (거치 3년)',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasRevenue', label: '매출 실적', check: 'required', description: '사업 영위 실적' },
      { field: 'yearsFromFounding', label: '업력', check: 'preferred', description: '업력에 따라 지원 유형 상이' },
      { field: 'hasVentureCert', label: '벤처/이노비즈', check: 'bonus', description: '인증기업 우대 금리' },
    ],
    website: 'https://www.kosmes.or.kr',
    description: '중소기업진흥공단의 저금리 정책자금. 혁신성장형, 긴급경영안정자금 등.',
  },
  {
    id: 'small_biz_tech',
    name: '중소기업기술혁신개발사업',
    agency: '중소벤처기업부',
    category: 'R&D',
    maxAmount: '최대 5억원',
    maxAmountNum: 500_000_000,
    supportType: '출연금',
    period: '2~3년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasRnd', label: 'R&D 역량', check: 'required', description: 'R&D 투자실적 및 연구인력' },
      { field: 'hasResearchInstitute', label: '연구소', check: 'preferred', description: '기업부설연구소 보유 우대' },
      { field: 'hasPatent', label: '기술력', check: 'preferred', description: '특허 등 기술성과물 보유' },
    ],
    website: 'https://www.smtech.go.kr',
    description: '기존 중소기업의 기술혁신을 위한 R&D 지원. 시장확대형, 공정개선형 등.',
  },
  {
    id: 'credit_guarantee',
    name: '기술보증기금 보증',
    agency: '기술보증기금(KIBO)',
    category: '보증',
    maxAmount: '최대 30억원',
    maxAmountNum: 3_000_000_000,
    supportType: '신용보증',
    period: '1~5년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasRnd', label: '기술역량', check: 'preferred', description: 'R&D 역량 또는 기술성 보유' },
      { field: 'hasPatent', label: '지식재산권', check: 'bonus', description: '특허, 실용신안 등 기술 IP' },
      { field: 'hasVentureCert', label: '벤처/이노비즈', check: 'bonus', description: '인증기업 보증 우대' },
    ],
    website: 'https://www.kibo.or.kr',
    description: '기술 기반 중소기업에 대한 신용보증 제공. 은행 대출 시 담보 역할.',
  },
  {
    id: 'manufacturing_innovation',
    name: '스마트공장 구축지원',
    agency: '중소벤처기업부 / 스마트제조혁신추진단',
    category: '사업화',
    maxAmount: '최대 1.5억원',
    maxAmountNum: 150_000_000,
    supportType: '보조금 (자부담 50%)',
    period: '1년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'isManufacturing', label: '제조업', check: 'required', description: '제조업 영위 기업' },
      { field: 'hasRevenue', label: '매출 실적', check: 'required', description: '사업 영위 실적' },
    ],
    website: 'https://www.smart-factory.kr',
    description: '제조 중소기업의 스마트공장 도입을 위한 보조금 지원.',
  },
  {
    id: 'green_transition',
    name: '탄소중립·그린뉴딜 지원사업',
    agency: '산업통상자원부',
    category: 'R&D',
    maxAmount: '최대 5억원',
    maxAmountNum: 500_000_000,
    supportType: '출연금',
    period: '2~3년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'isGreenBiz', label: '친환경 사업', check: 'required', description: '그린전환 관련 사업 영위' },
      { field: 'hasRnd', label: 'R&D 역량', check: 'preferred', description: 'R&D 투자실적 또는 연구인력' },
      { field: 'hasPatent', label: '기술력 보유', check: 'bonus', description: '친환경 기술 특허 보유' },
    ],
    website: 'https://www.motie.go.kr',
    description: '탄소중립 및 그린뉴딜 전환을 위한 기술개발 및 사업화 지원.',
  },
  {
    id: 'women_startup',
    name: '여성기업 성장지원사업',
    agency: '여성기업종합지원센터',
    category: '사업화',
    maxAmount: '최대 1억원',
    maxAmountNum: 100_000_000,
    supportType: '보조금',
    period: '1년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'isWomenOwned', label: '여성 대표', check: 'required', description: '여성이 대표이사인 기업' },
      { field: 'hasRevenue', label: '매출 실적', check: 'preferred', description: '사업 영위 실적' },
      { field: 'hasVentureCert', label: '벤처/이노비즈', check: 'bonus', description: '인증기업 가산점' },
    ],
    website: 'https://www.wbiz.or.kr',
    description: '여성기업의 성장과 경쟁력 강화를 위한 사업화 자금 및 멘토링 지원.',
  },
  {
    id: 'social_enterprise',
    name: '사회적기업 육성사업',
    agency: '고용노동부',
    category: '사업화',
    maxAmount: '인건비 + 사업개발비',
    maxAmountNum: 200_000_000,
    supportType: '보조금',
    period: '최대 5년',
    requirements: [
      { field: 'isSocialEnterprise', label: '사회적기업 인증', check: 'required', description: '사회적기업 인증 필수' },
      { field: 'hasRevenue', label: '사업 실적', check: 'preferred', description: '사회적 가치 창출 실적' },
      { field: 'isSmallBiz', label: '중소기업', check: 'preferred', description: '중소기업 규모' },
    ],
    website: 'https://www.socialenterprise.or.kr',
    description: '사회적기업의 일자리 창출 및 사업개발비 지원.',
  },
  {
    id: 'youth_startup',
    name: '청년창업사관학교',
    agency: '중소벤처기업부',
    category: '사업화',
    maxAmount: '최대 1억원',
    maxAmountNum: 100_000_000,
    supportType: '출연금',
    period: '1년',
    requirements: [
      { field: 'isYoungFounder', label: '청년 대표', check: 'required', description: '대표자 만 39세 이하' },
      { field: 'yearsFromFounding', label: '업력 3년 이내', check: 'required', description: '창업 3년 이내 기업' },
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasVentureCert', label: '벤처기업', check: 'bonus', description: '벤처기업 인증 가산' },
    ],
    website: 'https://www.kised.or.kr',
    description: '청년 예비창업자 및 초기 창업기업에 사업화 자금, 멘토링, 공간 제공.',
  },
  {
    id: 'local_special',
    name: '지역특화산업 육성사업',
    agency: '중소벤처기업부 / 지자체',
    category: 'R&D',
    maxAmount: '최대 3억원',
    maxAmountNum: 300_000_000,
    supportType: '출연금',
    period: '2~3년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'isRural', label: '지역 소재', check: 'required', description: '해당 지역 소재 기업' },
      { field: 'hasRnd', label: 'R&D 역량', check: 'preferred', description: 'R&D 투자 및 연구인력' },
      { field: 'hasRevenue', label: '매출 실적', check: 'preferred', description: '사업 영위 실적' },
    ],
    website: 'https://www.smtech.go.kr',
    description: '지역 특화산업의 경쟁력 강화를 위한 R&D 및 사업화 지원.',
  },
  {
    id: 'ip_biz',
    name: 'IP나래 (지식재산 사업화)',
    agency: '특허청',
    category: '사업화',
    maxAmount: '최대 3억원',
    maxAmountNum: 300_000_000,
    supportType: '출연금',
    period: '2년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasIPRights', label: 'IP 보유', check: 'required', description: '특허, 상표 등 지식재산권 보유' },
      { field: 'hasPatent', label: '특허 활용', check: 'preferred', description: 'IP를 활용한 사업화 계획' },
      { field: 'hasRnd', label: 'R&D 역량', check: 'bonus', description: 'R&D 투자 실적' },
    ],
    website: 'https://www.kipo.go.kr',
    description: '보유 IP를 활용한 사업화 촉진 및 제품 고도화 지원.',
  },
  {
    id: 'smart_commerce',
    name: '스마트상점 기술보급사업',
    agency: '중소벤처기업부 / 소상공인시장진흥공단',
    category: '사업화',
    maxAmount: '최대 3천만원',
    maxAmountNum: 30_000_000,
    supportType: '보조금 (자부담 10~30%)',
    period: '1년',
    requirements: [
      { field: 'isSmallBiz', label: '소상공인', check: 'required', description: '소상공인기본법상 소상공인' },
      { field: 'hasRevenue', label: '매출 실적', check: 'required', description: '사업 영위 실적' },
      { field: 'yearsFromFounding', label: '업력', check: 'preferred', description: '6개월 이상 영업' },
    ],
    website: 'https://www.semas.or.kr',
    description: '소상공인의 디지털 전환을 위한 키오스크, POS, 온라인마케팅 지원.',
  },
  {
    id: 'rural_revitalize',
    name: '농촌융복합산업 지원사업 (6차산업)',
    agency: '농림축산식품부',
    category: '사업화',
    maxAmount: '최대 5억원',
    maxAmountNum: 500_000_000,
    supportType: '보조금',
    period: '3년',
    requirements: [
      { field: 'isRural', label: '농촌 소재', check: 'required', description: '농촌 지역 소재 기업' },
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업 또는 농업인' },
      { field: 'hasRevenue', label: '사업 실적', check: 'preferred', description: '1차 생산 또는 가공 실적' },
      { field: 'hasIPRights', label: 'IP/브랜드', check: 'bonus', description: '상표, 브랜드 등록 가산' },
    ],
    website: 'https://www.mafra.go.kr',
    description: '농촌 융복합산업(6차산업) 육성을 위한 가공시설, 판매장, 체험장 구축 지원.',
  },
  {
    id: 'kotra_global',
    name: 'KOTRA 해외진출 종합지원',
    agency: 'KOTRA',
    category: '수출',
    maxAmount: '최대 5천만원',
    maxAmountNum: 50_000_000,
    supportType: '바우처',
    period: '1년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'isExporter', label: '수출 계획', check: 'required', description: '수출 의지 및 계획 보유' },
      { field: 'hasRevenue', label: '매출 실적', check: 'preferred', description: '사업 영위 실적' },
      { field: 'hasVentureCert', label: '벤처/이노비즈', check: 'bonus', description: '인증기업 우대' },
    ],
    website: 'https://www.kotra.or.kr',
    description: 'KOTRA 해외 네트워크를 활용한 시장조사, 바이어 발굴, 전시회 참가 지원.',
  },
  {
    id: 'innobiz_support',
    name: '이노비즈·메인비즈 지원사업',
    agency: '중소벤처기업부',
    category: '보증',
    maxAmount: '최대 20억원',
    maxAmountNum: 2_000_000_000,
    supportType: '보증 우대',
    period: '1~5년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasVentureCert', label: '이노비즈/메인비즈', check: 'required', description: '기술혁신형 중소기업 인증' },
      { field: 'hasRnd', label: 'R&D 투자', check: 'preferred', description: 'R&D 투자실적' },
      { field: 'hasPatent', label: '특허 보유', check: 'bonus', description: '특허 등 기술성과물 보유' },
    ],
    website: 'https://www.innobiz.net',
    description: '이노비즈·메인비즈 인증기업에 대한 보증 및 금융 우대 지원.',
  },
  {
    id: 'disaster_support',
    name: '재난피해 중소기업 긴급지원',
    agency: '중소벤처기업부',
    category: '정책자금',
    maxAmount: '최대 10억원',
    maxAmountNum: 1_000_000_000,
    supportType: '긴급 융자',
    period: '최대 5년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasRevenue', label: '재난 피해', check: 'required', description: '자연재해 또는 재난 피해 확인서' },
      { field: 'yearsFromFounding', label: '업력', check: 'preferred', description: '6개월 이상 사업 영위' },
    ],
    website: 'https://www.kosmes.or.kr',
    description: '자연재해, 감염병 등 재난 피해 중소기업에 긴급 경영안정자금 융자.',
  },
  {
    id: 'digital_transform',
    name: '비대면서비스 바우처',
    agency: '중소벤처기업부',
    category: '사업화',
    maxAmount: '최대 4백만원',
    maxAmountNum: 4_000_000,
    supportType: '바우처 (자부담 10%)',
    period: '6개월',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업 또는 소상공인' },
      { field: 'hasRevenue', label: '매출 실적', check: 'required', description: '사업 영위 실적' },
      { field: 'yearsFromFounding', label: '업력', check: 'preferred', description: '6개월 이상 영업' },
    ],
    website: 'https://www.k-voucher.kr',
    description: '중소기업·소상공인의 디지털 전환을 위한 솔루션 도입 바우처 지원.',
  },
  {
    id: 'esa_investment',
    name: 'ESG 경영 지원사업',
    agency: '중소벤처기업부',
    category: '사업화',
    maxAmount: '최대 5천만원',
    maxAmountNum: 50_000_000,
    supportType: '보조금',
    period: '1년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasRevenue', label: '매출 실적', check: 'required', description: '사업 영위 실적' },
      { field: 'isGreenBiz', label: 'ESG 관심', check: 'preferred', description: 'ESG 경영 의지 또는 환경경영 실적' },
      { field: 'hasVentureCert', label: '벤처/이노비즈', check: 'bonus', description: '인증기업 가산점' },
    ],
    website: 'https://www.sminfo.mss.go.kr',
    description: 'ESG 진단, 컨설팅, 인증 취득 등 중소기업의 ESG 경영 체계 구축 지원.',
  },
  // ===== 소상공인시장진흥공단 =====
  {
    id: 'small_merchant_fund',
    name: '소상공인 정책자금 (직접대출)',
    agency: '소상공인시장진흥공단',
    category: '정책자금',
    maxAmount: '최대 7천만원',
    maxAmountNum: 70_000_000,
    supportType: '저금리 직접대출',
    period: '5년 (거치 2년)',
    requirements: [
      { field: 'isSmallBiz', label: '소상공인', check: 'required', description: '상시근로자 5인 미만 (제조/건설/광업 10인 미만)' },
      { field: 'hasRevenue', label: '사업 영위', check: 'required', description: '사업자등록 후 실제 사업 영위 중' },
      { field: 'isCleanCredit', label: '신용 양호', check: 'required', description: '세금 체납 없고 연체 없는 자' },
    ],
    website: 'https://ols.semas.or.kr',
    description: '소상공인시장진흥공단에서 직접 대출하는 저금리 정책자금. 일반경영안정자금, 긴급경영자금 등.',
  },
  {
    id: 'small_merchant_guarantee',
    name: '소상공인 신용보증 지원',
    agency: '소상공인시장진흥공단',
    category: '정책자금',
    maxAmount: '최대 5천만원',
    maxAmountNum: 50_000_000,
    supportType: '신용보증서 발급',
    period: '1년 (갱신 가능)',
    requirements: [
      { field: 'isSmallBiz', label: '소상공인', check: 'required', description: '소상공인 요건 충족' },
      { field: 'hasRevenue', label: '영업 실적', check: 'required', description: '영업활동 중인 소상공인' },
      { field: 'isCleanCredit', label: '신용등급 양호', check: 'preferred', description: '신용등급 7등급 이상 권장' },
    ],
    website: 'https://www.semas.or.kr',
    description: '담보력 부족 소상공인에게 신용보증서를 발급하여 시중 은행 대출을 지원.',
  },
  {
    id: 'traditional_market',
    name: '전통시장 활성화 지원',
    agency: '소상공인시장진흥공단',
    category: '사업화',
    maxAmount: '최대 3억원',
    maxAmountNum: 300_000_000,
    supportType: '보조금',
    period: '1~3년',
    requirements: [
      { field: 'isSmallBiz', label: '전통시장 상인', check: 'required', description: '전통시장/상점가 등록 상인' },
      { field: 'hasRevenue', label: '시장 소속', check: 'required', description: '인정시장 소속 여부' },
    ],
    website: 'https://www.semas.or.kr',
    description: '전통시장 시설 현대화, 경영 혁신, 디지털 전환 지원. 상인회/시장 단위 신청.',
  },
  {
    id: 'small_startup_package',
    name: '소상공인 창업패키지 (신사업창업사관학교)',
    agency: '소상공인시장진흥공단',
    category: '사업화',
    maxAmount: '최대 1억원',
    maxAmountNum: 100_000_000,
    supportType: '교육+사업화자금',
    period: '6~12개월',
    requirements: [
      { field: 'isYoungFounder', label: '예비/초기 창업자', check: 'required', description: '예비창업자 또는 업력 3년 이내' },
      { field: 'isSmallBiz', label: '소상공인 해당', check: 'required', description: '소상공인 업종에 해당하는 사업' },
    ],
    website: 'https://www.semas.or.kr/web/board/webBoardList.kmdc?bCd=1087',
    description: '예비 소상공인에게 교육, 멘토링, 사업화 자금을 패키지로 지원. 전국 교육장 운영.',
  },
  // ===== 관광진흥개발기금 =====
  {
    id: 'tourism_fund',
    name: '관광진흥개발기금 융자',
    agency: '문화체육관광부/한국관광공사',
    category: '정책자금',
    maxAmount: '최대 30억원',
    maxAmountNum: 3_000_000_000,
    supportType: '저금리 융자',
    period: '10년 (거치 3년)',
    requirements: [
      { field: 'isSmallBiz', label: '관광사업체', check: 'required', description: '관광진흥법상 등록된 관광사업체' },
      { field: 'hasRevenue', label: '사업 실적', check: 'required', description: '관광사업 영위 실적' },
      { field: 'hasLicense', label: '관광사업 등록', check: 'required', description: '관광숙박, 관광객이용시설 등 등록' },
    ],
    website: 'https://fund.knto.or.kr',
    description: '관광시설 신축/증축/개보수, 관광사업 운영자금 등 저금리 융자. 호텔, 펜션, 관광지 등.',
  },
  {
    id: 'tourism_venture',
    name: '관광벤처사업 공모',
    agency: '한국관광공사',
    category: '사업화',
    maxAmount: '최대 5천만원',
    maxAmountNum: 50_000_000,
    supportType: '보조금+멘토링',
    period: '1년',
    requirements: [
      { field: 'yearsFromFounding', label: '업력 7년 이내', check: 'required', description: '관광분야 창업 7년 이내' },
      { field: 'isSmallBiz', label: '중소/소상공인', check: 'required', description: '중소기업 또는 소상공인' },
    ],
    website: 'https://kto.visitkorea.or.kr',
    description: '관광 분야 혁신 아이디어를 가진 스타트업/벤처에 사업화 자금 지원.',
  },
  // ===== 신용보증기금/기술보증기금 =====
  {
    id: 'kodit_startup',
    name: '신용보증기금 창업기업 보증',
    agency: '신용보증기금',
    category: '정책자금',
    maxAmount: '최대 30억원',
    maxAmountNum: 3_000_000_000,
    supportType: '신용보증',
    period: '1년 (갱신 가능)',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'yearsFromFounding', label: '업력 7년 이내', check: 'preferred', description: '창업 7년 이내 우대' },
      { field: 'isCleanCredit', label: '신용 양호', check: 'required', description: '금융기관 연체 없음' },
    ],
    website: 'https://www.kodit.co.kr',
    description: '담보력 부족 중소기업에 신용보증서 발급. 창업기업 우대 보증비율 적용.',
  },
  {
    id: 'kibo_tech',
    name: '기술보증기금 기술보증',
    agency: '기술보증기금',
    category: '정책자금',
    maxAmount: '최대 30억원',
    maxAmountNum: 3_000_000_000,
    supportType: '기술보증',
    period: '1년 (갱신 가능)',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasPatent', label: '기술력 보유', check: 'preferred', description: '특허, 기술개발 실적 등 기술력' },
      { field: 'isCleanCredit', label: '신용 양호', check: 'required', description: '금융기관 연체 없음' },
      { field: 'hasResearchInstitute', label: '연구인력', check: 'bonus', description: '연구소/전담부서 보유 시 우대' },
    ],
    website: 'https://www.kibo.or.kr',
    description: '기술력 우수 중소기업에 기술평가 기반 보증서 발급. IP 담보 대출 가능.',
  },
  // ===== 산업통상자원부/에너지 =====
  {
    id: 'energy_efficiency',
    name: '에너지이용합리화 자금',
    agency: '산업통상자원부/한국에너지공단',
    category: '정책자금',
    maxAmount: '최대 50억원',
    maxAmountNum: 5_000_000_000,
    supportType: '저금리 융자',
    period: '5년 (거치 3년)',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '에너지다소비업체 또는 중소기업' },
      { field: 'hasRevenue', label: '사업 실적', check: 'required', description: '에너지 절약 시설 투자 계획' },
      { field: 'isGreenBiz', label: '에너지절약 투자', check: 'preferred', description: '에너지 절약/신재생에너지 시설 투자' },
    ],
    website: 'https://www.energy.or.kr',
    description: '에너지 절약 시설 교체, 신재생에너지 설치, ESCO 사업 등에 저금리 융자.',
  },
  // ===== 고용노동부 =====
  {
    id: 'employment_subsidy',
    name: '고용촉진장려금',
    agency: '고용노동부',
    category: '사업화',
    maxAmount: '월 최대 80만원/인',
    maxAmountNum: 9_600_000,
    supportType: '고용장려금',
    period: '6~12개월',
    requirements: [
      { field: 'isSmallBiz', label: '사업주', check: 'required', description: '고용보험 가입 사업주' },
      { field: 'employeeCount', label: '고용 계획', check: 'required', description: '취업 취약계층 신규 고용 계획' },
    ],
    website: 'https://www.ei.go.kr',
    description: '고령자, 장애인, 여성가장 등 취약계층을 신규 고용한 사업주에게 장려금 지급.',
  },
  {
    id: 'workplace_innovation',
    name: '일터혁신 지원사업',
    agency: '고용노동부/노사발전재단',
    category: '사업화',
    maxAmount: '최대 2천만원',
    maxAmountNum: 20_000_000,
    supportType: '컨설팅+보조금',
    period: '6개월',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업 또는 중견기업' },
      { field: 'employeeCount', label: '상시 근로자', check: 'required', description: '상시근로자 1인 이상' },
    ],
    website: 'https://www.nosa.or.kr',
    description: '중소기업 근무환경 개선, 유연근무제 도입, 스마트공장 전환 등 컨설팅 지원.',
  },
  // ===== 농림축산식품부 =====
  {
    id: 'agri_venture',
    name: '농식품 벤처 창업 인큐베이팅',
    agency: '농림축산식품부/농업기술실용화재단',
    category: '사업화',
    maxAmount: '최대 1억원',
    maxAmountNum: 100_000_000,
    supportType: '사업화자금+멘토링',
    period: '1년',
    requirements: [
      { field: 'yearsFromFounding', label: '업력 7년 이내', check: 'required', description: '농식품 분야 창업 7년 이내' },
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '농식품 관련 중소기업 또는 예비창업자' },
      { field: 'isRural', label: '농식품 분야', check: 'preferred', description: '농업/식품/축산 관련 사업' },
    ],
    website: 'https://www.fact.or.kr',
    description: '농식품 분야 혁신 기술 기반 창업 지원. 교육, 멘토링, 사업화 자금 패키지.',
  },
  // ===== 과학기술정보통신부 =====
  {
    id: 'ict_rnd',
    name: 'ICT R&D 혁신바우처',
    agency: '과학기술정보통신부/IITP',
    category: 'R&D',
    maxAmount: '최대 3억원',
    maxAmountNum: 300_000_000,
    supportType: '출연금(바우처)',
    period: '1~2년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: 'ICT 분야 중소기업' },
      { field: 'hasRnd', label: 'ICT R&D', check: 'required', description: 'ICT 관련 R&D 계획' },
      { field: 'hasPatent', label: '기술력', check: 'preferred', description: '기존 ICT 기술 보유 시 우대' },
    ],
    website: 'https://www.iitp.kr',
    description: 'ICT 분야 중소기업의 기술개발을 바우처 형태로 지원. AI, 클라우드, 빅데이터 등.',
  },
  {
    id: 'content_fund',
    name: '콘텐츠 제작 지원',
    agency: '문화체육관광부/한국콘텐츠진흥원',
    category: '사업화',
    maxAmount: '최대 5억원',
    maxAmountNum: 500_000_000,
    supportType: '투자+보조금',
    period: '1~2년',
    requirements: [
      { field: 'isSmallBiz', label: '콘텐츠 기업', check: 'required', description: '콘텐츠 제작 중소기업' },
      { field: 'hasRevenue', label: '제작 실적', check: 'preferred', description: '콘텐츠 제작/유통 실적' },
    ],
    website: 'https://www.kocca.kr',
    description: '게임, 영상, 음악, 웹툰 등 콘텐츠 제작 자금 지원. 완성보증 보험 연계.',
  },
  // ===== 지자체/지역 =====
  {
    id: 'local_startup_fund',
    name: '지역 창업활성화 지원',
    agency: '각 지자체/창조경제혁신센터',
    category: '사업화',
    maxAmount: '최대 1억원 (지역별 상이)',
    maxAmountNum: 100_000_000,
    supportType: '보조금+공간지원',
    period: '1년',
    requirements: [
      { field: 'yearsFromFounding', label: '초기 창업자', check: 'required', description: '업력 3년 이내 또는 예비창업자' },
      { field: 'isSmallBiz', label: '소재지 요건', check: 'required', description: '해당 지자체 관내 사업장 소재' },
    ],
    website: 'https://ccei.creativekorea.or.kr',
    description: '전국 17개 창조경제혁신센터 + 지자체 자체 창업지원 프로그램. 지역별 특화사업.',
  },
  {
    id: 'free_zone',
    name: '경제자유구역 입주기업 지원',
    agency: '산업통상자원부/각 경제자유구역청',
    category: '사업화',
    maxAmount: '조세감면+보조금',
    maxAmountNum: 500_000_000,
    supportType: '조세감면+입지보조금',
    period: '최대 7년',
    requirements: [
      { field: 'isSmallBiz', label: '입주/투자 기업', check: 'required', description: '경제자유구역 입주 계획 기업' },
      { field: 'hasRevenue', label: '투자 계획', check: 'required', description: '시설 투자 계획 보유' },
      { field: 'hasIPRights', label: '외국인 투자', check: 'bonus', description: '외국인 투자기업 우대' },
    ],
    website: 'https://www.fez.go.kr',
    description: '인천, 부산, 광양만권 등 경제자유구역 입주기업 세제 감면, 임대료 감면, 보조금.',
  },
  // ===== 중소벤처기업부 추가 =====
  {
    id: 'global_startup',
    name: 'Born2Global (글로벌 창업지원)',
    agency: '중소벤처기업부/Born2Global센터',
    category: '수출',
    maxAmount: '최대 2억원',
    maxAmountNum: 200_000_000,
    supportType: '보조금+해외진출지원',
    period: '1년',
    requirements: [
      { field: 'isSmallBiz', label: '중소/스타트업', check: 'required', description: 'ICT/기술기반 중소기업' },
      { field: 'hasPatent', label: '글로벌 기술', check: 'preferred', description: '글로벌 경쟁력 있는 기술/서비스' },
      { field: 'yearsFromFounding', label: '업력 7년 이내', check: 'preferred', description: '초기 스타트업 우대' },
    ],
    website: 'https://www.born2global.com',
    description: '글로벌 진출 유망 스타트업 선발 후 해외 IR, 마케팅, 법률자문 등 패키지 지원.',
  },
  {
    id: 'reshoring',
    name: '유턴기업(리쇼어링) 지원',
    agency: '산업통상자원부/KOTRA',
    category: '정책자금',
    maxAmount: '최대 10억원',
    maxAmountNum: 1_000_000_000,
    supportType: '보조금+세제감면',
    period: '3년',
    requirements: [
      { field: 'isSmallBiz', label: '해외 진출 기업', check: 'required', description: '해외에 2년 이상 운영 사업장 보유 (보유했던) 기업' },
      { field: 'hasRevenue', label: '국내 복귀 계획', check: 'required', description: '국내 생산시설 신설/증설 계획' },
    ],
    website: 'https://www.motie.go.kr',
    description: '해외에서 국내로 복귀하는 기업에 이전비, 설비, 인력채용 등 지원. 세제 감면 혜택.',
  },
  {
    id: 'material_parts_equip',
    name: '소재·부품·장비 경쟁력 강화',
    agency: '산업통상자원부',
    category: 'R&D',
    maxAmount: '최대 20억원',
    maxAmountNum: 2_000_000_000,
    supportType: '출연금(R&D)',
    period: '3~5년',
    requirements: [
      { field: 'isSmallBiz', label: '중소/중견기업', check: 'required', description: '소부장 분야 중소/중견기업' },
      { field: 'hasRnd', label: 'R&D 역량', check: 'required', description: '소재/부품/장비 R&D 역량' },
      { field: 'hasPatent', label: '핵심 기술', check: 'preferred', description: '관련 특허 보유 시 가산' },
      { field: 'hasResearchInstitute', label: '연구소', check: 'preferred', description: '기업부설연구소 또는 연구전담부서' },
    ],
    website: 'https://www.keit.re.kr',
    description: '일본 수출규제 대응으로 시작된 소부장 국산화/경쟁력 강화 R&D 사업.',
  },
];
