// =============================================================================
// 정책자금 프로그램 데이터베이스
// =============================================================================

export interface FundProgram {
  id: string;
  name: string;
  agency: string;           // 운영기관
  category: string;         // 분류 (R&D, 사업화, 수출, 정책자금 등)
  maxAmount: string;        // 최대 지원 금액 표시
  maxAmountNum: number;     // 비교용 숫자 (원)
  supportType: string;      // 지원 유형 (출연금, 융자, 보증 등)
  period: string;           // 지원 기간
  requirements: FundRequirement[];
  website: string;
  description: string;
}

export interface FundRequirement {
  field: string;
  label: string;
  check: 'required' | 'preferred' | 'bonus';
  description: string;
}

export const FUND_PROGRAMS: FundProgram[] = [
  {
    id: 'tips',
    name: 'TIPS (민간투자주도형 기술창업지원)',
    agency: '중소벤처기업부',
    category: 'R&D',
    maxAmount: '최대 10억원',
    maxAmountNum: 1_000_000_000,
    supportType: '출연금(R&D) + 엔젤매칭',
    period: '3년',
    requirements: [
      { field: 'yearsFromFounding', label: '업력 7년 이내', check: 'required', description: '설립 후 7년 이내 기업' },
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasPatent', label: '기술력 보유', check: 'preferred', description: '특허, 기술 등 핵심 기술 보유' },
      { field: 'hasResearchInstitute', label: '연구소/전담부서', check: 'bonus', description: '기업부설연구소 또는 R&D 전담부서' },
      { field: 'hasVentureCert', label: '벤처기업 인증', check: 'bonus', description: '벤처기업 확인서 보유 시 가산' },
    ],
    website: 'https://www.jointips.or.kr',
    description: 'TIPS 운영사의 투자를 받은 기업에 R&D 자금을 매칭 지원. 민간 엔젤투자 연계 필수.',
  },
  {
    id: 'startup_growth',
    name: '창업성장기술개발사업',
    agency: '중소벤처기업부',
    category: 'R&D',
    maxAmount: '최대 3억원',
    maxAmountNum: 300_000_000,
    supportType: '출연금',
    period: '2년',
    requirements: [
      { field: 'yearsFromFounding', label: '업력 7년 이내', check: 'required', description: '창업 7년 이내 중소기업' },
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasRnd', label: 'R&D 역량', check: 'preferred', description: 'R&D 투자실적 또는 연구인력 보유' },
      { field: 'hasPatent', label: '기술력 보유', check: 'bonus', description: '특허, 논문 등 기술성과물' },
    ],
    website: 'https://www.smtech.go.kr',
    description: '창업 초기 기술개발을 지원하는 정부 R&D 과제. 디딤돌/전략형 트랙.',
  },
  {
    id: 'export_voucher',
    name: '수출바우처',
    agency: '중소벤처기업부 / KOTRA',
    category: '수출',
    maxAmount: '최대 1억원',
    maxAmountNum: 100_000_000,
    supportType: '바우처(수출활동비)',
    period: '1년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'isExporter', label: '수출 의지/실적', check: 'preferred', description: '수출 실적 또는 수출 계획 보유' },
      { field: 'hasRevenue', label: '매출 실적', check: 'required', description: '일정 매출 실적 보유' },
      { field: 'hasVentureCert', label: '벤처/이노비즈', check: 'bonus', description: '인증기업 가산점' },
    ],
    website: 'https://www.exportvoucher.com',
    description: '해외마케팅, 통번역, 해외인증 등 수출활동에 바우처 지원.',
  },
  {
    id: 'sme_policy_fund',
    name: '중소기업 정책자금 (직접대출)',
    agency: '중소벤처기업진흥공단',
    category: '정책자금',
    maxAmount: '최대 100억원',
    maxAmountNum: 10_000_000_000,
    supportType: '저금리 융자',
    period: '최대 8년 (거치 3년)',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasRevenue', label: '매출 실적', check: 'required', description: '사업 영위 실적' },
      { field: 'yearsFromFounding', label: '업력', check: 'preferred', description: '업력에 따라 지원 유형 상이' },
      { field: 'hasVentureCert', label: '벤처/이노비즈', check: 'bonus', description: '인증기업 우대 금리' },
    ],
    website: 'https://www.kosmes.or.kr',
    description: '중소기업진흥공단의 저금리 정책자금. 혁신성장형, 긴급경영안정자금 등.',
  },
  {
    id: 'small_biz_tech',
    name: '중소기업기술혁신개발사업',
    agency: '중소벤처기업부',
    category: 'R&D',
    maxAmount: '최대 5억원',
    maxAmountNum: 500_000_000,
    supportType: '출연금',
    period: '2~3년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasRnd', label: 'R&D 역량', check: 'required', description: 'R&D 투자실적 및 연구인력' },
      { field: 'hasResearchInstitute', label: '연구소', check: 'preferred', description: '기업부설연구소 보유 우대' },
      { field: 'hasPatent', label: '기술력', check: 'preferred', description: '특허 등 기술성과물 보유' },
    ],
    website: 'https://www.smtech.go.kr',
    description: '기존 중소기업의 기술혁신을 위한 R&D 지원. 시장확대형, 공정개선형 등.',
  },
  {
    id: 'credit_guarantee',
    name: '기술보증기금 보증',
    agency: '기술보증기금(KIBO)',
    category: '보증',
    maxAmount: '최대 30억원',
    maxAmountNum: 3_000_000_000,
    supportType: '신용보증',
    period: '1~5년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasRnd', label: '기술역량', check: 'preferred', description: 'R&D 역량 또는 기술성 보유' },
      { field: 'hasPatent', label: '지식재산권', check: 'bonus', description: '특허, 실용신안 등 기술 IP' },
      { field: 'hasVentureCert', label: '벤처/이노비즈', check: 'bonus', description: '인증기업 보증 우대' },
    ],
    website: 'https://www.kibo.or.kr',
    description: '기술 기반 중소기업에 대한 신용보증 제공. 은행 대출 시 담보 역할.',
  },
  {
    id: 'manufacturing_innovation',
    name: '스마트공장 구축지원',
    agency: '중소벤처기업부 / 스마트제조혁신추진단',
    category: '사업화',
    maxAmount: '최대 1.5억원',
    maxAmountNum: 150_000_000,
    supportType: '보조금 (자부담 50%)',
    period: '1년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'isManufacturing', label: '제조업', check: 'required', description: '제조업 영위 기업' },
      { field: 'hasRevenue', label: '매출 실적', check: 'required', description: '사업 영위 실적' },
    ],
    website: 'https://www.smart-factory.kr',
    description: '제조 중소기업의 스마트공장 도입을 위한 보조금 지원.',
  },
  {
    id: 'green_transition',
    name: '탄소중립·그린뉴딜 지원사업',
    agency: '산업통상자원부',
    category: 'R&D',
    maxAmount: '최대 5억원',
    maxAmountNum: 500_000_000,
    supportType: '출연금',
    period: '2~3년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'isGreenBiz', label: '친환경 사업', check: 'required', description: '그린전환 관련 사업 영위' },
      { field: 'hasRnd', label: 'R&D 역량', check: 'preferred', description: 'R&D 투자실적 또는 연구인력' },
      { field: 'hasPatent', label: '기술력 보유', check: 'bonus', description: '친환경 기술 특허 보유' },
    ],
    website: 'https://www.motie.go.kr',
    description: '탄소중립 및 그린뉴딜 전환을 위한 기술개발 및 사업화 지원.',
  },
  {
    id: 'women_startup',
    name: '여성기업 성장지원사업',
    agency: '여성기업종합지원센터',
    category: '사업화',
    maxAmount: '최대 1억원',
    maxAmountNum: 100_000_000,
    supportType: '보조금',
    period: '1년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'isWomenOwned', label: '여성 대표', check: 'required', description: '여성이 대표이사인 기업' },
      { field: 'hasRevenue', label: '매출 실적', check: 'preferred', description: '사업 영위 실적' },
      { field: 'hasVentureCert', label: '벤처/이노비즈', check: 'bonus', description: '인증기업 가산점' },
    ],
    website: 'https://www.wbiz.or.kr',
    description: '여성기업의 성장과 경쟁력 강화를 위한 사업화 자금 및 멘토링 지원.',
  },
  {
    id: 'social_enterprise',
    name: '사회적기업 육성사업',
    agency: '고용노동부',
    category: '사업화',
    maxAmount: '인건비 + 사업개발비',
    maxAmountNum: 200_000_000,
    supportType: '보조금',
    period: '최대 5년',
    requirements: [
      { field: 'isSocialEnterprise', label: '사회적기업 인증', check: 'required', description: '사회적기업 인증 필수' },
      { field: 'hasRevenue', label: '사업 실적', check: 'preferred', description: '사회적 가치 창출 실적' },
      { field: 'isSmallBiz', label: '중소기업', check: 'preferred', description: '중소기업 규모' },
    ],
    website: 'https://www.socialenterprise.or.kr',
    description: '사회적기업의 일자리 창출 및 사업개발비 지원.',
  },
  {
    id: 'youth_startup',
    name: '청년창업사관학교',
    agency: '중소벤처기업부',
    category: '사업화',
    maxAmount: '최대 1억원',
    maxAmountNum: 100_000_000,
    supportType: '출연금',
    period: '1년',
    requirements: [
      { field: 'isYoungFounder', label: '청년 대표', check: 'required', description: '대표자 만 39세 이하' },
      { field: 'yearsFromFounding', label: '업력 3년 이내', check: 'required', description: '창업 3년 이내 기업' },
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasVentureCert', label: '벤처기업', check: 'bonus', description: '벤처기업 인증 가산' },
    ],
    website: 'https://www.kised.or.kr',
    description: '청년 예비창업자 및 초기 창업기업에 사업화 자금, 멘토링, 공간 제공.',
  },
  {
    id: 'local_special',
    name: '지역특화산업 육성사업',
    agency: '중소벤처기업부 / 지자체',
    category: 'R&D',
    maxAmount: '최대 3억원',
    maxAmountNum: 300_000_000,
    supportType: '출연금',
    period: '2~3년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'isRural', label: '지역 소재', check: 'required', description: '해당 지역 소재 기업' },
      { field: 'hasRnd', label: 'R&D 역량', check: 'preferred', description: 'R&D 투자 및 연구인력' },
      { field: 'hasRevenue', label: '매출 실적', check: 'preferred', description: '사업 영위 실적' },
    ],
    website: 'https://www.smtech.go.kr',
    description: '지역 특화산업의 경쟁력 강화를 위한 R&D 및 사업화 지원.',
  },
  {
    id: 'ip_biz',
    name: 'IP나래 (지식재산 사업화)',
    agency: '특허청',
    category: '사업화',
    maxAmount: '최대 3억원',
    maxAmountNum: 300_000_000,
    supportType: '출연금',
    period: '2년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasIPRights', label: 'IP 보유', check: 'required', description: '특허, 상표 등 지식재산권 보유' },
      { field: 'hasPatent', label: '특허 활용', check: 'preferred', description: 'IP를 활용한 사업화 계획' },
      { field: 'hasRnd', label: 'R&D 역량', check: 'bonus', description: 'R&D 투자 실적' },
    ],
    website: 'https://www.kipo.go.kr',
    description: '보유 IP를 활용한 사업화 촉진 및 제품 고도화 지원.',
  },
  {
    id: 'smart_commerce',
    name: '스마트상점 기술보급사업',
    agency: '중소벤처기업부 / 소상공인시장진흥공단',
    category: '사업화',
    maxAmount: '최대 3천만원',
    maxAmountNum: 30_000_000,
    supportType: '보조금 (자부담 10~30%)',
    period: '1년',
    requirements: [
      { field: 'isSmallBiz', label: '소상공인', check: 'required', description: '소상공인기본법상 소상공인' },
      { field: 'hasRevenue', label: '매출 실적', check: 'required', description: '사업 영위 실적' },
      { field: 'yearsFromFounding', label: '업력', check: 'preferred', description: '6개월 이상 영업' },
    ],
    website: 'https://www.semas.or.kr',
    description: '소상공인의 디지털 전환을 위한 키오스크, POS, 온라인마케팅 지원.',
  },
  {
    id: 'rural_revitalize',
    name: '농촌융복합산업 지원사업 (6차산업)',
    agency: '농림축산식품부',
    category: '사업화',
    maxAmount: '최대 5억원',
    maxAmountNum: 500_000_000,
    supportType: '보조금',
    period: '3년',
    requirements: [
      { field: 'isRural', label: '농촌 소재', check: 'required', description: '농촌 지역 소재 기업' },
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업 또는 농업인' },
      { field: 'hasRevenue', label: '사업 실적', check: 'preferred', description: '1차 생산 또는 가공 실적' },
      { field: 'hasIPRights', label: 'IP/브랜드', check: 'bonus', description: '상표, 브랜드 등록 가산' },
    ],
    website: 'https://www.mafra.go.kr',
    description: '농촌 융복합산업(6차산업) 육성을 위한 가공시설, 판매장, 체험장 구축 지원.',
  },
  {
    id: 'kotra_global',
    name: 'KOTRA 해외진출 종합지원',
    agency: 'KOTRA',
    category: '수출',
    maxAmount: '최대 5천만원',
    maxAmountNum: 50_000_000,
    supportType: '바우처',
    period: '1년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'isExporter', label: '수출 계획', check: 'required', description: '수출 의지 및 계획 보유' },
      { field: 'hasRevenue', label: '매출 실적', check: 'preferred', description: '사업 영위 실적' },
      { field: 'hasVentureCert', label: '벤처/이노비즈', check: 'bonus', description: '인증기업 우대' },
    ],
    website: 'https://www.kotra.or.kr',
    description: 'KOTRA 해외 네트워크를 활용한 시장조사, 바이어 발굴, 전시회 참가 지원.',
  },
  {
    id: 'innobiz_support',
    name: '이노비즈·메인비즈 지원사업',
    agency: '중소벤처기업부',
    category: '보증',
    maxAmount: '최대 20억원',
    maxAmountNum: 2_000_000_000,
    supportType: '보증 우대',
    period: '1~5년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasVentureCert', label: '이노비즈/메인비즈', check: 'required', description: '기술혁신형 중소기업 인증' },
      { field: 'hasRnd', label: 'R&D 투자', check: 'preferred', description: 'R&D 투자실적' },
      { field: 'hasPatent', label: '특허 보유', check: 'bonus', description: '특허 등 기술성과물 보유' },
    ],
    website: 'https://www.innobiz.net',
    description: '이노비즈·메인비즈 인증기업에 대한 보증 및 금융 우대 지원.',
  },
  {
    id: 'disaster_support',
    name: '재난피해 중소기업 긴급지원',
    agency: '중소벤처기업부',
    category: '정책자금',
    maxAmount: '최대 10억원',
    maxAmountNum: 1_000_000_000,
    supportType: '긴급 융자',
    period: '최대 5년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasRevenue', label: '재난 피해', check: 'required', description: '자연재해 또는 재난 피해 확인서' },
      { field: 'yearsFromFounding', label: '업력', check: 'preferred', description: '6개월 이상 사업 영위' },
    ],
    website: 'https://www.kosmes.or.kr',
    description: '자연재해, 감염병 등 재난 피해 중소기업에 긴급 경영안정자금 융자.',
  },
  {
    id: 'digital_transform',
    name: '비대면서비스 바우처',
    agency: '중소벤처기업부',
    category: '사업화',
    maxAmount: '최대 4백만원',
    maxAmountNum: 4_000_000,
    supportType: '바우처 (자부담 10%)',
    period: '6개월',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업 또는 소상공인' },
      { field: 'hasRevenue', label: '매출 실적', check: 'required', description: '사업 영위 실적' },
      { field: 'yearsFromFounding', label: '업력', check: 'preferred', description: '6개월 이상 영업' },
    ],
    website: 'https://www.k-voucher.kr',
    description: '중소기업·소상공인의 디지털 전환을 위한 솔루션 도입 바우처 지원.',
  },
  {
    id: 'esa_investment',
    name: 'ESG 경영 지원사업',
    agency: '중소벤처기업부',
    category: '사업화',
    maxAmount: '최대 5천만원',
    maxAmountNum: 50_000_000,
    supportType: '보조금',
    period: '1년',
    requirements: [
      { field: 'isSmallBiz', label: '중소기업', check: 'required', description: '중소기업기본법상 중소기업' },
      { field: 'hasRevenue', label: '매출 실적', check: 'required', description: '사업 영위 실적' },
      { field: 'isGreenBiz', label: 'ESG 관심', check: 'preferred', description: 'ESG 경영 의지 또는 환경경영 실적' },
      { field: 'hasVentureCert', label: '벤처/이노비즈', check: 'bonus', description: '인증기업 가산점' },
    ],
    website: 'https://www.sminfo.mss.go.kr',
    description: 'ESG 진단, 컨설팅, 인증 취득 등 중소기업의 ESG 경영 체계 구축 지원.',
  },
];
